### PR TITLE
Re-enable status bar on disposal

### PR DESCRIPTION
**Pull request by mcoolidge**

### CODE REVIEW

**Comment by duytq94** [comment]
From https://github.com/duytq94/flutter-intro-slider/issues/49
Thanks for your contribution, but this pull request doesn't fix the problem
If you would like to show the status bar, just set shouldHideStatusBar = false is enough

**Comment by duytq94** [comment]
Thanks for your contribution but I tested and it does not bring the status bar back when navigating to a new screen.

**Comment by mcoolidge** [comment]
Thats strange, it worked when I referenced it from my project. Are you using the example project or something else?

**Comment by duytq94** [comment]
I switched to your branch and run the example but nothing happens when I navigate to a new screen. The issue happens on both iOS and Android.
You can test by running the example on your branch.
Btw, my new screen is wrapped by Scaffold, I'm not sure if it affects this problem.

**Pull request closed without merging**
