### PR TITLE
add a behavior for the vertical scrollbar

### PR DESCRIPTION
**Pull request by esskar**
This will allow to specify how the vertical scrollbar should behave. This is similar to #77 . I did not see that pull request before i made my changes.

### CODE REVIEW

**Comment by duytq94** [comment]
Thank you, I just merged https://github.com/duytq94/flutter-intro-slider/pull/77 so we should close your PR since they're the same?

**Comment by esskar** [comment]
It was not the same? with my PR you could set if the scrollbar is always shown, never, or only when scrolling.

**Comment by duytq94** [comment]
I got what you mean, could you help me update your PR by replace the old scrollbar I just merged at https://github.com/duytq94/flutter-intro-slider/pull/77 with yours?

**Comment by duytq94** [comment]
Thanks for your request 👍

**Pull request merged**
