### PR TITLE
chore(Rebuild) fix issue StatefulWidget not rebuild when parent update

### PR DESCRIPTION
**Pull request by trunghieuvn**
Hi @duytq94 
We need localize for this screen intro_slider.
but when I change language and rebuild this screen, it not change.

please review this issue.

### CODE REVIEW

**Comment by trunghieuvn** [comment]
Hi @duytq94  please take a look

**Comment by duytq94** [comment]
Hi @trunghieuvn 
Many thanks for your PR, I think we should find out why setState don't work instead of this work around solution.
Anyway, if I change `styleSkipBtn` not `nameSkipBtn`, does your solution working?

**Comment by trunghieuvn** [comment]
Hi @duytq94 

Currently widget not rebuild when parent set new value and rebuild

**Comment by duytq94** [comment]
Are you mentioned about it's not rebuild when hot reload, maybe like these issue
https://github.com/duytq94/flutter-intro-slider/issues/59
https://github.com/duytq94/flutter-intro-slider/issues/30

**Comment by trunghieuvn** [comment]
Yep, we need implement did update widget for statefull widget, make sure when parent change data and need rebuild.

**Comment by duytq94** [comment]
So I think we should find out why it's not rebuild when parent update, using `didUpdateWidget` is just a work around.

**Comment by duytq94** [comment]
And your code just check
`
if (oldWidget.nameSkipBtn != widget.nameSkipBtn) {
...
`
If others attribute (widthSkipBtn, namePrevBtn...) it doesn't work?

**Review by theifedayo — CHANGES_REQUESTED** [review]
check for conflict and resolve

**Pull request closed without merging**
